/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AboutWeb {
    }
    interface AppRoot {
    }
    interface MyComponent {
    }
    interface SiteButton {
    }
    interface TextWithColor {
    }
    interface WebAbout {
    }
    interface WebHeader {
    }
}
declare global {
    interface HTMLAboutWebElement extends Components.AboutWeb, HTMLStencilElement {
    }
    var HTMLAboutWebElement: {
        prototype: HTMLAboutWebElement;
        new (): HTMLAboutWebElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSiteButtonElement extends Components.SiteButton, HTMLStencilElement {
    }
    var HTMLSiteButtonElement: {
        prototype: HTMLSiteButtonElement;
        new (): HTMLSiteButtonElement;
    };
    interface HTMLTextWithColorElement extends Components.TextWithColor, HTMLStencilElement {
    }
    var HTMLTextWithColorElement: {
        prototype: HTMLTextWithColorElement;
        new (): HTMLTextWithColorElement;
    };
    interface HTMLWebAboutElement extends Components.WebAbout, HTMLStencilElement {
    }
    var HTMLWebAboutElement: {
        prototype: HTMLWebAboutElement;
        new (): HTMLWebAboutElement;
    };
    interface HTMLWebHeaderElement extends Components.WebHeader, HTMLStencilElement {
    }
    var HTMLWebHeaderElement: {
        prototype: HTMLWebHeaderElement;
        new (): HTMLWebHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "about-web": HTMLAboutWebElement;
        "app-root": HTMLAppRootElement;
        "my-component": HTMLMyComponentElement;
        "site-button": HTMLSiteButtonElement;
        "text-with-color": HTMLTextWithColorElement;
        "web-about": HTMLWebAboutElement;
        "web-header": HTMLWebHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AboutWeb {
    }
    interface AppRoot {
    }
    interface MyComponent {
    }
    interface SiteButton {
    }
    interface TextWithColor {
    }
    interface WebAbout {
    }
    interface WebHeader {
    }
    interface IntrinsicElements {
        "about-web": AboutWeb;
        "app-root": AppRoot;
        "my-component": MyComponent;
        "site-button": SiteButton;
        "text-with-color": TextWithColor;
        "web-about": WebAbout;
        "web-header": WebHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-web": LocalJSX.AboutWeb & JSXBase.HTMLAttributes<HTMLAboutWebElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "site-button": LocalJSX.SiteButton & JSXBase.HTMLAttributes<HTMLSiteButtonElement>;
            "text-with-color": LocalJSX.TextWithColor & JSXBase.HTMLAttributes<HTMLTextWithColorElement>;
            "web-about": LocalJSX.WebAbout & JSXBase.HTMLAttributes<HTMLWebAboutElement>;
            "web-header": LocalJSX.WebHeader & JSXBase.HTMLAttributes<HTMLWebHeaderElement>;
        }
    }
}
